### ISSUE TITLE
Incorrect reference resolved

### ISSUE THREAD

**Issue by dziamid** [sghribi/loopback-fixtures#11]
Hey, i noticed that sometimes references get resolved incorrectly.
```
Bar:
  bar1:
    title: {{name.findName}}

FooBar:
  foobar1:
    title: {{name.findName}}

Baz:
  baz1:
    title: {{name.findName}}
    bar: @bar1 // references "@foobar1" instead.
```

PS Lmk if you need further help to reproduce this. Great library anyway!
