### ISSUE TITLE
Add reference to array object? 

### ISSUE THREAD

**Issue by sokphea-chea** [sghribi/loopback-fixtures#22]
Example I have two model in loopback
record.json
```
{
......
"properties": {
    "vaccine_ids": {
      "type": [
        "object"
      ]
    }
......
}
```
vaccine.json
```
{
......
  "properties": {
    "name": {
      "type": "string"
    },
    "decription": {
      "type": "string"
    },
    "minInjection": {
      "type": "number"
    }
  }
......
}
```

I have this data.yml

```
Vaccine:
  vaccine{1..10}:
    name: "Vaccine{@}"
    decription: "{{lorem.sentence}}"
    minInjection: "{{random.number(3)}}"
```

```
Record:
    record{1..30}:
        vaccine_ids: ???
```

Could you tell me how to add the vaccine_ids reference to vaccine? Thank you.
